@startuml
class Manager {
    + {static} Initialize() : void
    + {static} Close() : void
}
Manager -> "Instance" Manager
Manager --> CaptureManager
Manager --> DeviceCaptureManager
Manager ---> SpectrogramGenerator
@enduml
