@startuml
!include ./AnalyseAudio-Pinfo-simplified/Models/AudioStream.puml
!include ./AnalyseAudio-Pinfo-simplified/Models/Capture/CaptureManager.puml
!include ./AnalyseAudio-Pinfo-simplified/Models/Capture/DeviceCapture.puml
!include ./AnalyseAudio-Pinfo-simplified/Models/Capture/DeviceCaptureManager.puml
!include ./AnalyseAudio-Pinfo-simplified/Models/Capture/DeviceMicrophone.puml
!include ./AnalyseAudio-Pinfo-simplified/Models/Capture/DeviceSpeaker.puml
!include ./AnalyseAudio-Pinfo-simplified/Models/Capture/DeviceWasapi.puml
!include ./AnalyseAudio-Pinfo-simplified/Models/Capture/DeviceWaveIn.puml
!include ./AnalyseAudio-Pinfo-simplified/ViewModels/CaptureViewModel.puml
CaptureViewModel -> DeviceCaptureManager

@enduml
