@startuml

!include ./AnalyseAudio-Pinfo-simplified/Views/Pages/CapturePage.xaml.puml
!include ./AnalyseAudio-Pinfo-simplified/Views/Pages/ConsolePage.xaml.puml
!include ./AnalyseAudio-Pinfo-simplified/Views/Pages/SpectrogramConfigPage.xaml.puml
!include ./AnalyseAudio-Pinfo-simplified/Views/Pages/SettingsPage.xaml.puml
!include ./AnalyseAudio-Pinfo-simplified/Views/Pages/PianoPage.xaml.puml
!include ./AnalyseAudio-Pinfo-simplified/Views/Piano/KeyboardElement.xaml.puml
!include ./AnalyseAudio-Pinfo-simplified/Views/Piano/KeyboardNote.xaml.puml

@enduml
